using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows.Forms;
using ESRI.ArcGIS.Carto; //For ILayer
using ESRI.ArcGIS.Display; // for ISymbol
using System.Diagnostics;

namespace PlantPickerAddIn
{
    public class PlantSpecies : ESRI.ArcGIS.Desktop.AddIns.ComboBox
    {
        public PlantSpecies()
        {
            foreach (string plant in plants)
                Add(plant);
        }

        protected override void OnSelChange(int cookie)
        {
            base.OnSelChange(cookie);
            BuildPlantLayer(Value);
        }

        private void BuildPlantLayer(string plant)
        {
            LayerFileClass layerFile = new LayerFileClass();
            ILayer layer;
            //string filename = "W:\\ARO\\GIS\\PlantDemo\\Plant.lyr";
            string filename = "C:\\1_Projects\\PlantDemo\\Plant.lyr";
            try
            {
                layerFile.Open(filename);
                layer = layerFile.Layer;
            }
            catch (Exception ex)
            {
                Debug.Print("swallowed exception\n" + ex);
                MessageBox.Show("Could not find '" + filename + "'", "File Not Found", MessageBoxButtons.OK, MessageBoxIcon.Error);
                layer = null;
            }

            if (layer != null && layer is IFeatureLayerDefinition2)
            {
                layer.Name = plant;
                RandomizeMarkerColor(layer);
                string definitionQuery = "\"ref_taxon_Common_Name\" = '" + plant.Replace("'","''") + "'";
                ((IFeatureLayerDefinition2)layer).DefinitionExpression = definitionQuery;
                ArcMap.Document.AddLayer(layer);
            }
        }

        private void RandomizeMarkerColor(ILayer layer)
        {
            IGeoFeatureLayer geoLayer = layer as IGeoFeatureLayer;
            if (geoLayer == null)
                return;
            ISimpleRenderer renderer = geoLayer.Renderer as ISimpleRenderer;
            if (renderer == null)
                return;
            IMarkerSymbol symbol = renderer.Symbol as IMarkerSymbol;
            if (symbol == null)
                return;
            IRgbColor color = new RgbColorClass();
            Random rand = new Random();
            color.Red = rand.Next(256);
            color.Blue = rand.Next(256);
            color.Green = rand.Next(256);
            color.UseWindowsDithering = true;
            symbol.Color = color;
        }

        private string[] plants =
        {
            "Alaska bellheather",
            "Alaska bluegrass",
            "Alaska bog willow",
            "Alaska curved woodrush",
            "Alaska draba",
            "Alaska moonwort",
            "Alaska springbeauty",
            "Alaska starwort",
            "Alaska wild rhubarb",
            "Alaskan douglasia",
            "Alaskan mountain-avens",
            "Alaskan wheatgrass",
            "Alaskan wheatgrass",
            "Aleutian cress",
            "Aleutian mountainheath",
            "Aleutian violet",
            "alpine azalea",
            "alpine bearberry",
            "alpine bistort",
            "alpine bittercress",
            "alpine bluegrass",
            "alpine bulrush",
            "alpine clubmoss",
            "alpine draba",
            "alpine fescue",
            "alpine groundsel",
            "alpine ladyfern",
            "alpine meadow-rue",
            "alpine milkvetch",
            "alpine mountainsorrel",
            "alpine pondweed",
            "alpine pussytoes",
            "alpine saxifrage",
            "alpine smelowskia",
            "alpine sweetgrass",
            "alpine sweetvetch",
            "alpine timothy",
            "alpine woodsia",
            "Altai fescue",
            "American alpine speedwell",
            "American mannagrass",
            "American pasqueflower",
            "American red raspberry",
            "American rockbrake",
            "American sloughgrass",
            "American speedwell",
            "American thorow wax",
            "American yellowrocket",
            "Anadyr draba",
            "apetalous catchfly",
            "apetalous catchfly",
            "arctic alpine fleabane",
            "arctic alpine forget-me-not",
            "arctic aster",
            "arctic bellflower",
            "arctic blackberry",
            "arctic blackberry",
            "arctic bluegrass",
            "arctic bluegrass",
            "arctic catchfly",
            "arctic cinquefoil",
            "arctic cottongrass",
            "arctic dock",
            "arctic eyebright",
            "arctic groundsel",
            "arctic lupine",
            "arctic pearlwort",
            "arctic pennycress",
            "arctic primrose",
            "arctic rush",
            "arctic starflower",
            "arctic stitchwort",
            "arctic sweet coltsfoot",
            "arctic willow",
            "arctic woodrush",
            "arctic yellow violet",
            "arrowleaf ragwort",
            "Asian forget-me-not",
            "Austrian draba",
            "autumn dwarf gentian",
            "Baffin fescue",
            "balsam poplar",
            "Barclay's willow",
            "Barratt's willow",
            "barrenground willow",
            "beachhead iris",
            "beaked sedge",
            "beautiful sandwort",
            "beauverd spirea",
            "Bebb willow",
            "Bellardi bog sedge",
            "Bering chickweed",
            "Bering hairgrass",
            "Bigelow's sedge",
            "bitter fleabane",
            "black crowberry",
            "black spruce",
            "blackandwhite sedge",
            "blackish oxytrope",
            "blite goosefoot",
            "blueberry willow",
            "bluejoint",
            "bluntleaf sandwort",
            "bluntleaved orchid",
            "bog adder's-mouth orchid",
            "bog blueberry",
            "bog Labrador tea",
            "bog rosemary",
            "bog yellowcress",
            "boreal alopecurus",
            "boreal bog sedge",
            "boreal draba",
            "boreal locoweed",
            "boreal sagebrush",
            "boreal starwort",
            "boreal sweetvetch",
            "boreal yarrow",
            "bristleleaf sedge",
            "bristlystalked sedge",
            "brittle bladderfern",
            "broadleaf arnica",
            "broadleaf cattail",
            "brownish sedge",
            "buckbean",
            "bulblet-bearing water hemlock",
            "bunchberry dogwood",
            "Buxbaum's sedge",
            "Canadian burnet",
            "capitate lousewort",
            "capitate sedge",
            "captiate valerian",
            "chamisso sedge",
            "chestnut rush",
            "ciliate saxifrage",
            "circumpolar sedge",
            "claspleaf twistedstalk",
            "closedhead sedge",
            "cloudberry",
            "club spikemoss",
            "clubmoss mountain heather",
            "coastal sand sedge",
            "common alplily",
            "common bladderwort",
            "common butterwort",
            "common cowparsnip",
            "common dandelion",
            "common dandelion",
            "common dandelion",
            "common duckweed",
            "common juniper",
            "common mare's-tail",
            "common moonwort",
            "common spikerush",
            "common woodrush",
            "coon's tail",
            "Crawford's sedge",
            "creeping buttercup",
            "creeping sedge",
            "creeping sibbaldia",
            "cuckoo flower",
            "curly sedge",
            "curlytop knotweed",
            "cursed buttercup",
            "curved woodrush",
            "cushion draba",
            "Dahurian willowherb",
            "dandelion",
            "darkbrown sedge",
            "downy ryegrass",
            "Drummond's anemone",
            "Drummond's mountain-avens",
            "Drummond's rockcress",
            "Drummond's rush",
            "dwarf alpine hawksbeard",
            "dwarf arctic ragwort",
            "dwarf birch",
            "dwarf fireweed",
            "dwarf marsh violet",
            "dwarf scouringrush",
            "dwarf water lily",
            "Edwards' mock wallflower",
            "eightpetal mountain-avens",
            "elegant hawksbeard",
            "elegant Indian paintbrush",
            "elegant milkvetch",
            "elegant stitchwort",
            "elk sedge",
            "Enander's sedge",
            "English sundew",
            "entireleaf mountain-avens",
            "entireleaf mountain-avens",
            "Eschscholtz's buttercup",
            "fairy slipper",
            "false candytuft",
            "false mountain willow",
            "false toadflax",
            "feltleaf willow",
            "felwort",
            "fewflower fumewort",
            "fewflower meadow-rue",
            "fewflower spikerush",
            "fewseeded bog sedge",
            "field horsetail",
            "field locoweed",
            "field sagewort",
            "fineleaf pondweed",
            "fir clubmoss",
            "fireleaf leptarrhena",
            "fireweed",
            "firmleaf willow",
            "flatleaf bladderwort",
            "flatstem pondweed",
            "flat-top draba",
            "fleshy dandelion",
            "fleshy starwort",
            "floating marsh marigold",
            "forked wormwood",
            "fourpart dwarf gentian",
            "fowl bluegrass",
            "fragile rockbrake",
            "fragile sedge",
            "fragrant woodfern",
            "Fries' pussytoes",
            "fringed brome",
            "fringed willowherb",
            "fuscate groundsel",
            "garden sorrel",
            "glacier avens",
            "glaucous bluegrass",
            "Gmelin's buttercup",
            "golden dock",
            "golden draba",
            "golden sedge",
            "goosegrass sedge",
            "Gorman's dwarf-primrose",
            "grassleaf springbeauty",
            "grayleaf draba",
            "grayleaf willow",
            "greater creeping spearwort",
            "green alder",
            "green false hellebore",
            "greenflowered wintergreen",
            "Greenland primrose",
            "groundcedar",
            "hairlike sedge",
            "hairy butterwort",
            "halberd willow",
            "heartleaf saxifrage",
            "high northern buttercup",
            "hoary yellowcress",
            "Holboell's rockcress",
            "hooded ladies'-tresses",
            "Hooker's cinquefoil",
            "Hornemann's willowherb",
            "Huddelson's locoweed",
            "ice cold buttercup",
            "icegrass",
            "Indian milkvetch",
            "inland sedge",
            "island purslane",
            "Jacob's-ladder",
            "Jakutsk snowparsley",
            "Jordal's locoweed",
            "Kamchatica rockcress",
            "Kamchatka fritillary",
            "Kamchatka rhododendron",
            "Kellogg's sedge",
            "Kentucky bluegrass",
            "Kentucky bluegrass",
            "kinnikinnick",
            "Kjellmans groundsel",
            "Kotzebue's grass of Parnassus",
            "Krause's sedge",
            "Labrador lousewort",
            "lanceleaf grapefern",
            "lancepod draba",
            "Langsdorf's lousewort",
            "Lapland buttercup",
            "Lapland cornel",
            "Lapland poppy",
            "lapland reedgrass",
            "Lapland rosebay",
            "Lapland sedge",
            "largeflower fleabane",
            "largeflowered wintergreen",
            "largefruit catchfly",
            "largeleaf avens",
            "larkspurleaf monkshood",
            "larkspurleaf monkshood",
            "Laxmann's milkvetch",
            "leafystem saxifrage",
            "least willow",
            "leatherleaf",
            "ledge stonecrop",
            "lesser blackscale sedge",
            "lesser bladderwort",
            "lesser panicled sedge",
            "lesser rattlesnake plantain",
            "lingonberry",
            "little green sedge",
            "little yellowrattle",
            "littletree willow",
            "liverleaf wintergreen",
            "livid sedge",
            "long beechfern",
            "longbract frog orchid",
            "longleaf starwort",
            "longpod stitchwort",
            "longstalk draba",
            "longstalk starwort",
            "longstem sandwort",
            "low northern sedge",
            "Mackenzie Valley mannagrass",
            "Mackenzie's water hemlock",
            "Macoun's draba",
            "Macoun's poppy",
            "Macoun's woodroot",
            "manyflower sedge",
            "marsh arrowgrass",
            "marsh felwort",
            "marsh fleabane",
            "marsh grass of Parnassus",
            "marsh horsetail",
            "marsh Labrador tea",
            "marsh skullcap",
            "marsh willowherb",
            "matted starwort",
            "Maydell's oxytrope",
            "McConnell's poppy",
            "meadow bistort",
            "meadow horsetail",
            "Menzies' campion",
            "merckia",
            "Mertens' oxytrope",
            "milkflower willowherb",
            "milky draba",
            "Mingan moonwort",
            "Mistassini primrose",
            "moor rush",
            "moss campion",
            "mountain bladderfern",
            "mountain deathcamas",
            "mountain hairgrass",
            "mountain harebell",
            "mountain moonwort",
            "mountain stitchwort",
            "mud sedge",
            "muskeg lousewort",
            "muskroot",
            "nakedstem wallflower",
            "narcissus anemone",
            "narrowleaf arnica",
            "narrowleaf bur-reed",
            "narrowleaf grapefern",
            "narrowleaf saw-wort",
            "narrowleaf saw-wort",
            "needle spikerush",
            "netleaf willow",
            "nodding arnica",
            "nodding beggartick",
            "nodding locoweed",
            "nodding saxifrage",
            "nodding waternymph",
            "Nootka lupine",
            "northern asphodel",
            "northern bedstraw",
            "northern bentgrass",
            "northern black currant",
            "northern bog aster",
            "northern bog sedge",
            "northern bur-reed",
            "northern cluster sedge",
            "northern dandelion",
            "northern fescue",
            "northern golden saxifrage",
            "northern green orchid",
            "northern green rush",
            "northern groundcone",
            "northern Jacob's-ladder",
            "northern kittentails",
            "northern larkspur",
            "northern moonwort",
            "northern singlespike sedge",
            "northern starwort",
            "northern sweetgrass",
            "northern tansymustard",
            "northern twayblade",
            "northern water-starwort",
            "northern woodrush",
            "northland cottonsedge",
            "Northwest Territory sedge",
            "Norwegian cinquefoil",
            "Nutzotin milkvetch",
            "obtuse sedge",
            "Oeder's lousewort",
            "official burnet",
            "Ogotoruk Creek ragwort",
            "one-cone clubmoss",
            "oneflower cinquefoil",
            "oneflower fleabane",
            "Pacific anemone",
            "Pacific willow",
            "pale gentian",
            "pale poppy",
            "Pallas' wallflower",
            "partridgefoot",
            "Peel River catchfly",
            "pendantgrass",
            "Pennsylvania buttercup",
            "Pennsylvania cinquefoil",
            "pimpernel willowherb",
            "pincushion plant",
            "pink campion",
            "Piper's woodrush",
            "polar milkvetch",
            "polar willow",
            "Porcupine River thimbleweed",
            "Porsild's saxifrage",
            "Port Clarence Indian paintbrush",
            "prairie flax",
            "prairie sagewort",
            "prickly rose",
            "Pumpelly's brome",
            "purple bittercress",
            "purple fleabane",
            "purple marshlocks",
            "purple mountain saxifrage",
            "purple reedgrass",
            "purple wormwood",
            "pygmy buttercup",
            "pygmy gentian",
            "pygmy pussytoes",
            "pygmyflower rockjasmine",
            "Pyrenean sedge",
            "quaking aspen",
            "quillwort",
            "Rainier draba",
            "rannoch-rush",
            "red baneberry",
            "red cottongrass",
            "red currant",
            "red fescue",
            "red fruit bearberry",
            "redstem saxifrage",
            "reflexed saxifrage",
            "resin birch",
            "ribbonleaf pondweed",
            "Richardson's brookfoam",
            "Richardson's fescue",
            "Richardson's pondweed",
            "Richardson's willow",
            "Robbins' milkvetch",
            "rock sedge",
            "rockdwelling sedge",
            "Rocky Mountain fescue",
            "Rocky Mountain goldenrod",
            "Rocky Mountain pond-lily",
            "rooted poppy",
            "Ross' avens",
            "rosy pussytoes",
            "rough bentgrass",
            "round sedge",
            "roundleaf sundew",
            "rufous woodrush",
            "running clubmoss",
            "russet buffaloberry",
            "rusty woodsia",
            "ryegrass sedge",
            "sageleaf willow",
            "sandbar willow",
            "Scamman's oxytrope",
            "Scamman's springbeauty",
            "scentbottle",
            "Scots false asphodel",
            "Scouler's willow",
            "seacoast angelica",
            "seaside arrowgrass",
            "seep monkeyflower",
            "Selkirk's violet",
            "Setchell's willow",
            "sheathed sedge",
            "shortawn foxtail",
            "shortcoal bluegrass",
            "shortleaved sedge",
            "shortray fleabane",
            "shortspike watermilfoil",
            "shortstalk sedge",
            "showy alpine forget-me-not",
            "showy pussytoes",
            "shrubby cinquefoil",
            "shy wallflower",
            "Siberian bog sedge",
            "Siberian oatgrass",
            "Siberian polypody",
            "Siberian spikemoss",
            "Siberian yarrow",
            "sidebells wintergreen",
            "Sierra larkspur",
            "silverberry",
            "silvery sedge",
            "simple bog sedge",
            "single delight",
            "skeletonleaf willow",
            "skullcap speedwell",
            "skunk currant",
            "slender cottongrass",
            "slender mountain sandwort",
            "slender wheatgrass",
            "slenderfruit willowherb",
            "slimstem reedgrass",
            "small blacktip ragwort",
            "small bur-reed",
            "small cranberry",
            "small enchanter's nightshade",
            "small floating mannagrass",
            "small pondweed",
            "small saxifrage",
            "smallawned sedge",
            "smallflowered anemone",
            "smallflowered woodrush",
            "smooth draba",
            "smooth northern-rockcress",
            "smooth woodsia",
            "smoothstem sedge",
            "snow arnica",
            "snow buttercup",
            "snow cinquefoil",
            "snow pearlwort",
            "snowbed draba",
            "snowline wintergreen",
            "soft fissurewort",
            "softleaf sedge",
            "softstem bulrush",
            "sparrowegg lady's slipper",
            "sparseflower sedge",
            "spike sedge",
            "spike trisetum",
            "spiked saxifrage",
            "spiked woodrush",
            "spiny phlox",
            "spotted lady's slipper",
            "spreading woodfern",
            "Sprouting Leaf willow",
            "squashberry",
            "star duckweed",
            "sticky tofieldia",
            "stiff clubmoss",
            "stiffstem saxifrage",
            "streamside fleabane",
            "subalpine fleabane",
            "subarctic ladyfern",
            "sudetic lousewort",
            "surefoot buttercup",
            "swamp boreal-daisy",
            "sweetflower rockjasmine",
            "sweetgale",
            "tall bluebells",
            "tall cottongrass",
            "tall Jacob's-ladder",
            "tamarack",
            "tealeaf willow",
            "thickspike wheatgrass",
            "thinleaf alder",
            "thinleaf cottonsedge",
            "thread rush",
            "threadleaf crowfoot",
            "three toothed saxifrage",
            "threehulled rush",
            "threelobe beggarticks",
            "threepetal bedstraw",
            "threepetal bedstraw",
            "thymeleaf saxifrage",
            "Tilesius' wormwood",
            "timber oatgrass",
            "toad rush",
            "tree groundpine",
            "trianglelobe moonwort",
            "tuberous springbeauty",
            "tufted alpine saxifrage",
            "tufted bulrush",
            "tufted hairgrass",
            "tufted loosestrife",
            "tundra fescue",
            "tundra milkvetch",
            "tundra wildrye",
            "tussock cottongrass",
            "twinflower",
            "twinflower sandwort",
            "twocolor sedge",
            "twoflower cinquefoil",
            "twoflowered rush",
            "twotipped sedge",
            "umbel bittercress",
            "umbrella starwort",
            "undergreen willow",
            "Vahl's Alkali Grass",
            "variableleaf pondweed",
            "variegated scouringrush",
            "variegated sedge",
            "varileaf cinquefoil",
            "vernal water-starwort",
            "viscid locoweed",
            "Wahlenberg's woodrush",
            "water arum",
            "water birch",
            "water horsetail",
            "water knotweed",
            "water sedge",
            "waterawlwort",
            "weak arctic sedge",
            "weak saxifrage",
            "weaselsnout",
            "wedgeleaf primrose",
            "western arctic shootingstar",
            "western buttercup",
            "western cordilleran bunchberry",
            "western oakfern",
            "western touch-me-not",
            "whiplash saxifrage",
            "white adder's-mouth orchid",
            "white arctic mountain heather",
            "white cottongrass",
            "white spruce",
            "white-lipped lousewort",
            "whorled lousewort",
            "whorl-leaf watermilfoil",
            "wideleaf arctic woodrush",
            "wideleaf polargrass",
            "wild chives",
            "Williams' sedge",
            "wood bluegrass",
            "woodland draba",
            "woodland horsetail",
            "woolly geranium",
            "woolly hawkweed",
            "woolly lousewort",
            "woollyfruit sedge",
            "Wright's golden saxifrage",
            "yellow arctic draba",
            "yellow avens",
            "yellow coralroot",
            "yellow marsh marigold",
            "yellow marsh saxifrage",
            "yellow mountainheath",
            "yellow thimbleweed",
            "yellowdot saxifrage",
            "Yukon fringed gentian",
            "Yukon groundsel",
            "Yukon sedge",
            "Yukon stitchwort",
        };
    }
}
